//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicalDBEntities : DbContext
    {
        public MedicalDBEntities()
            : base("name=MedicalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppointmentTable> AppointmentTables { get; set; }
        public virtual DbSet<DoctorTable> DoctorTables { get; set; }
        public virtual DbSet<MedicationListTable> MedicationListTables { get; set; }
        public virtual DbSet<MessageTable> MessageTables { get; set; }
        public virtual DbSet<PatientTable> PatientTables { get; set; }
        public virtual DbSet<TestsTable> TestsTables { get; set; }
        public virtual DbSet<UsersTable> UsersTables { get; set; }
    }
}
