//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageTable
    {
        public int MessageID { get; set; }
        public string MessageTo { get; set; }
        public string MessageFrom { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Message { get; set; }
    }
}
