//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestsTable
    {
        public int TestID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string TestResults { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public Nullable<int> DoctorID { get; set; }
    }
}
